### ISSUE TITLE
Bro-tie is down

### ISSUE THREAD

**Issue by gkiely** [letsgetrandy/brototype#33]
Getting a 403

**Comment by seriema** [comment]
Still down. And I was just proposing my team to use it! @letsgetrandy help us, bro! =D

**Comment by fgarci03** [comment]
yo yo @letsgetrandy dude!

+1 wut @seriema sed!

**Comment by deltreey** [comment]
brotie uses brototype's alias feature.  I'm fairly certain you could do it manually if you have to.  In the meantime, I'll see if I can mimic the brotie site and maybe host a mirror

**Comment by fgarci03** [comment]
@deltreey Thanks. I could do it, but if a better code (and tested) is available, I would prefer to use it :+1:

**Comment by deltreey** [comment]
I'll see if I can carve out some time tonight

**Comment by deltreey** [comment]
I looked into it.  The guy who owns brotie appears to be: jdauriemma who's github according to his website is @bignimbus so I'm hoping he catches this.  I didn't see a repo for the brotie site or any examples of it being used so I'd be building it from scratch at this point.  I don't know how to do that and don't have time to figure it out right now sadly.  Hopefully @bignimbus will open source the code at some point and we can all host mirrors.

**Comment by pepperthecat** [comment]
http://pepperthecat.github.io/brotie/

github.com/pepperthecat/brotie/

Found the source code and duplicated it with author's permission.  Appears to work well.  Enjoy!

**Comment by gkiely** [comment]
Thanks bro's glad we could get this sorted. Special thanks to @pepperthecat for setting up the new mirror.

**Comment by deltreey** [comment]
@pepperthecat I put in some pull requests to get that bro-tie up to date with the latest fieatures.  Just a little ping to let ya know.
