### ISSUE TITLE
Version that doesn't make source code look like written by 12-year-old idiots?

### ISSUE THREAD

**Issue by jimbo1qaz** [letsgetrandy/brototype#46]
This is a useful program using an ass-backwards and idiotic naming scheme. Code is meant to be used, not laughed at and burnt in a fire. If you keep writing libraries for illiterate 12-year-olds, I will have to create a renamed fork.

**Comment by deltreey** [comment]
if you need to use the tool and don't like the naming convention, you're welcome to use bro-tie
http://pepperthecat.github.io/brotie/
also...
[!haters](http://www.dumblittleman.com/wp-content/uploads/2015/03/latest.jpg)

**Comment by doot0** [comment]
Your hateful comments are totally useless. If you don't agree with the philosophy of the project, don't use it. Simple as. Go complain on Hacker News or something.

**Comment by jimbo1qaz** [comment]
![cancer_meme](https://cloud.githubusercontent.com/assets/913957/11451893/09c3421c-958a-11e5-8509-fbc81920896c.jpg)
