### ISSUE TITLE
This should be part of a larger library called brodash.

### ISSUE THREAD

**Issue by adjohu** [letsgetrandy/brototype#51]
I think my words speak for themselves.

**Comment by tj-commits** [comment]
I definitely agree and will start working on this library right now.
We have to make it as 10x as possible using libraries like [`Not.js`](https://npmjs.com/package/@not-js/not)

**Comment by tj-commits** [comment]
How should the API work, however?

**Comment by tj-commits** [comment]
Let's discuss this on the [new github repo](https://github.com/tj-commits/brodash)

**Comment by tj-commits** [comment]
why is this closed
