### ISSUE TITLE
Crashed on doYouEven with null

### ISSUE THREAD

**Issue by anorudes** [letsgetrandy/brototype#56]
Hello, i created a small util for app
```
export const hasIn = (obj = {}, path) => {
  return bro(obj).doYouEven(path);
};
```
Then i try this code:
```
!hasIn(post, 'test.0.test')
```
post isn't undefined, post = { test: null } 
After i have the message in console with text:
```
Cannot read property '0' of null
```

Can you help me resolve this problem?

**Comment by anorudes** [comment]
Oh, i understood, it's not working with "null", only undefined

**Comment by deltreey** [comment]
interesting situation.  I might even call this a bug.  What say you @letsgetrandy

**Comment by Plloi** [comment]
The crash happens in iCanHAz here: `item = item[props[i]];`
when trying to assign a subproperty of null to item
